stock:
  token: JbJPA0QvqjIbKPWj9YLTwKiAbRFpIO1jkjweHMLG
  url:
    get-symbols: https://api.stockdata.org/v1/entity/search?search=%s&api_token=%s
    stock-quotes: https://api.stockdata.org/v1/data/quote?symbols=%s&api_token=%s
    eod-multiple: https://api.stockdata.org/v1/data/eod/multiple?symbols=%s&api_token=%s&date=%s

server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: account
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

security:
  jwt:
    expiration: 600
    secret: c2VjcmV0